name: Atualizar Idade

on:
  schedule:
    - cron: '0 0 * * *' # Rodar uma vez por dia, mas pode ser ajustado

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Calcular idade e atualizar README
      run: |
        # Data de nascimento no formato AAAA-MM-DD
        nascimento="2005-10-23"
        
        # Calcular idade
        idade=$(date -d "$nascimento" +%Y)
        idade_atual=$(date +%Y)
        idade_final=$((idade_atual - idade))

        # Substituir a tag no README.md
        sed -i "s|<!-- AGE -->|$idade_final|g" README.md

    - name: Commit e push de alterações no README
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'Seu Nome'
        author_email: 'seuemail@example.com'
        message: 'Atualizando a idade no README'
