name: Atualizar Idade no README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Rodar script de atualização de idade
        run: |
          python atualizar_idade.py

      - name: Configurar Git para push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Commit e Push com GitHub Token
        run: |
          git add README.md
          git commit -m "Atualiza idade no README"
          git push origin HEAD:main
